# Generated by Django 4.2.7 on 2026-02-17 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(choices=[('Turbo', 'Turbo'), ('Sencillo', 'Sencillo'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('numero_entregas', models.IntegerField()),
                ('facturacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('validado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
