# Generated by Django 4.2.7 on 2026-02-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
    ]
